version: '3.8'

services:

  percona:
    image: percona:8.0
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=qwerty
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - data.percona:/var/lib/mysql
    ports:
      - "3306:3306"

  postgres:
    image: postgres:14.1
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=pguser
    volumes:
      - data.postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  data.percona:
    name: data.percona
  data.postgres:
    name: data.postgres